name: Build Docker Image

on:
  push:
    paths:
      - pyfreezer/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login --username danielshaulov --password $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull latest tag
        run: docker pull danielshaulov/pyfreezer:latest
      - name: Build the Docker image
        run: docker build --cache-from danielshaulov/pyfreezer:latest pyfreezer --tag pyfreezer:latest
      - name: Push the docker image
        run: docker push danielshaulov/pyfreezer:latest
      - name: Freeze example
        run: docker run -v ${PWD}/example:/code pyfreezer:latest /code/example.py
      - name: Archive frozen example
        uses: actions/upload-artifact@v1
        with:
          name: frozen-example
          path: ./example/example
      - name: Run example
        run: ./example/example
