name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Pull latest tag
        run: docker pull danielshaulov/pyfreezer:latest
      - name: Build the Docker image
        run: docker build --cache-from danielshaulov/pyfreeze:latest pyfreezer --tag pyfreezer:latest
      - name: Freeze example
        run: docker run -v ${PWD}/example:/code pyfreezer:latest /code/example.py
      - name: Archive frozen example
        uses: actions/upload-artifact@v1
        with:
          name: frozen-example
          path: ./example/example
      - name: Run example
        run: ./example/example
