name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build pyfreezer --tag pyfreezer:latest
      - name: Freeze example
        run: docker run -v ${PWD}/example:/code pyfreezer:latest /code/example.py
      - name: Archive frozen example
        uses: actions/upload-artifact@v1
        with:
          name: frozen-example
          path: ./example/example
      - name: Run example
        run: ./example/example
