name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build pyfreezer --tag pyfreezer:latest
        docker run -v ${PWD}/example:/code pyfreezer:latest /code/example.py
        ./example/example
